/*
* generated by Xtext
*/
package net.ivoa.pdl.pdls;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PdlsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return net.ivoa.pdl.pdls.ui.internal.PdlsActivator.getInstance().getInjector("net.ivoa.pdl.pdls.Pdls");
	}
	
}
