/*
 * generated by Xtext
 */
package net.ivoa.pdl.pdls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PdlsUiModule extends net.ivoa.pdl.pdls.ui.AbstractPdlsUiModule {
	public PdlsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
