/*
 * generated by Xtext
 */
package net.ivoa.pdl.pdls;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PdlsRuntimeModule extends net.ivoa.pdl.pdls.AbstractPdlsRuntimeModule {

}
