/*
* generated by Xtext
*/
package net.ivoa.pdl.pdls;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PdlsStandaloneSetup extends PdlsStandaloneSetupGenerated{

	public static void doSetup() {
		new PdlsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

