/*
 * generated by Xtext
 */
package net.ivoa.pdl.pdls.ui.contentassist

import net.ivoa.pdl.pdls.ui.contentassist.AbstractPdlsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PdlsProposalProvider extends AbstractPdlsProposalProvider {
}
