/*
* generated by Xtext
*/
package net.ivoa.pdl.pdls.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PdlsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("net/ivoa/pdl/pdls/parser/antlr/internal/InternalPdls.tokens");
	}
}
